<a href="https://colab.research.google.com/github/jaiz23/Big-Data-Analytics/blob/main/icp3_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
# 1.  np.random().randint will create ndarray with random numbers between the given range and the number elements in array is determined by size parameter.
arr = np.random.randint(1,21,size=15)
print(arr)

[ 9  4 12 10 15  4 15 15  4 18 11 14  1  2 18]


In [ ]:
# 2. reshape function change the shape of the ndarray with the specified shape. first parameter is row and second parameter is column.
# Array size should be rows * column, Then only it will change the shape of ndarray.
arrReshaped = arr.reshape(3,5)

In [ ]:
print(arrReshaped)

[[12 20  6  6  4]
 [13  8  3 17 15]
 [ 4 12 11 19  8]]


In [ ]:
# 3. To change max element in each row, we can use max() function with axis =1 which checks the max value for each row and keepsdim=True returns the array with reduced axes.
# With the help of boolean masking we can change max value in each row with 0.

In [ ]:
row_max = arrReshaped.max(axis=1,keepdims=True)


In [ ]:
boolean_mask = arrReshaped == row_max

In [ ]:
print(boolean_mask)

[[False False  True False False]
 [False  True  True False False]
 [False  True False False False]]


In [ ]:
arrReshaped[boolean_mask] = 0

In [ ]:
print(arrReshaped)

[[ 9  4  0 10  0]
 [ 4  0  0  4  0]
 [11  0  1  2  0]]


Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [ ]:
arr2 = np.arange(12,dtype=np.int32).reshape(4,3)

In [ ]:
# np.arange() function create a array within a range of values. we can define datatype of array with dtype parameter.
# The ask is to define 4-byte integer so int32 is 4 byte integer. (one byte = 8 bits. 4 bytes = 32 bits).
# reshape() function modify the dimension of array.

In [ ]:
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# shape

In [ ]:
print(arr2.shape)

(4, 3)


In [ ]:
# type of array

In [ ]:
print(type(arr2))

<class 'numpy.ndarray'>


In [ ]:
# data type of array

In [ ]:
print(arr2.dtype)

int32


c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]



In [ ]:
arr3 = np.array([[3,-2],[1,0]])

In [ ]:
arr3 = np.array([[3, -2],
                   [1,  0]])
eigenvalues, eigenvectors = np.linalg.eig(arr3)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [ ]:
arr4 = np.array([[0,1,2],[3,4,5]])

In [ ]:
diag_sum = 0
rows, cols = arr4.shape

for i in range(min(rows, cols)):  # ensure we stay within bounds for non-square matrices
    diag_sum += arr4[i][i]

print("Sum of diagonal elements:-", diag_sum)

Sum of diagonal elements:- 4


Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [ ]:
arr5 = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print("Original Array:\n", arr5)
reshaped_arr = arr5.reshape(2, 3)
print("Reshaped 2x3 Array:\n", reshaped_arr)

Original Array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped 2x3 Array:
 [[1 2 3]
 [4 5 6]]
